---

- name: install package
  package:
    name: "{{ chrony_packages }}"
    state: present

- name: get information
  chrony:
    command: "{{ chrony_service.executable }}"
    parameters:
      - --version
  register: chrony_information

- name: define chrony version
  set_fact:
    chrony_version: "{{ chrony_information.version }}"
    chrony_major_version: "{{ chrony_information.major_version }}"
  when:
    - chrony_information.rc == 0

- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/chrony.fact
    mode: 0755

- name: disable conflicting services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  register: disable_service_result
  failed_when:
    - disable_service_result is failed
    - not 'Could not find the requested service' in disable_service_result.msg
  loop:
    - ntp
    - ntpd
    - ntpsec
    - openntpd
    - systemd-timesyncd

...
