---

- name: start and enable service
  ansible.builtin.service:
    name: "{{ chrony_service.name }}"
    state: "{{ chrony_service.state | default('started') }}"
    enabled: "{{ chrony_service.enabled | default(true) | bool }}"
  notify:
    - query the systemd journal

...
