---

- name: flush handlers at this point to avoid double restart
  meta: flush_handlers

- name: start and enable service
  service:
    name: "{{ chrony_service.name }}"
    state: "{{ chrony_service.state | default('started') }}"
    enabled: "{{ chrony_service.enabled | default(true) | bool }}"
  ignore_errors: true
  register: _restart_result

- name: journal
  shell: |
    journalctl -n 400
  register: _service_result

- name: debug journal
  debug:
    msg: "{{ _service_result.stdout }}"

...
