---

- name: reload systemctl daemon
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == 'systemd'

- name: restart service
  service:
    name: "{{ chrony_service.name }}"
    state: restarted
  ignore_errors: true
  register: _WTF

- name: d
  debug:
    msg: "{{ _WTF }}"

...
