---

- name: reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr == 'systemd'

- name: restart service
  ansible.builtin.service:
    name: "{{ chrony_service.name }}"
    state: restarted
  ignore_errors: true
  register: restarted
  notify:
    - query the systemd journal

- name: query the systemd journal
  bodsch.systemd.journalctl:
    identifier: chrony
    lines: 150
  register: journalctl
  when:
    - restarted is defined
    - restarted.failed
    - chrony_query_journald
    - ansible_service_mgr == 'systemd'
  notify:
    - journalctl output

- name: journalctl output
  ansible.builtin.debug:
    msg: "{{ journalctl.stdout }}"
  when:
    journalctl.stdout is defined

...
