---

- name: reload systemctl daemon
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == 'systemd'

- name: restart service
  service:
    name: "{{ chrony_service.name }}"
    state: restarted

...
