---

- name: reload systemctl daemon
  systemd:
    daemon_reload: true
  when:
    - ansible_service_mgr == 'systemd'

- name: restart service
  service:
    name: "{{ chrony_service.name }}"
    state: restarted
  ignore_errors: true
  register: _restart_result
  notify:
    - debug restart
    - journal

- name: debug restart
  debug:
    msg: "{{ _restart_result }}"

- name: journal
  shell: |
    journalctl -n 400
  register: _restart_result
  notify:
    - debug journal

- name: debug journal
  debug:
    msg: "{{ _restart_result }}"

...
